GET http://localhost:3000/books

###
GET http://localhost:3000/books/3

###
POST http://localhost:3000/books
Content-Type: application/json

{
    "title" : "EE",
    "ISBN" : "ISBN-5",
    "publishedDate" : "2023-03-05",
    "author" : "EEE"    
}

###
PUT http://localhost:3000/books/54
Content-Type: application/json

{
    "title": "FF",
    "ISBN" : "ISBN-4",
    "publishedDate":"2023-02-02",
    "author": "FFF"
}

###
DELETE http://localhost:3000/books/22





